### ISSUE TITLE
Portable Mobs Requires Update

### ISSUE THREAD

**Issue by TheRTGGaming** [Dremoline/PortableMobs#4] opened 2023-03-15 10:59 UTC
**Version info**
Minecraft 1.19.2
Portable Mobs 1.1.1-forge-mc1.19

**Describe the bug**
The mod Requires SuperMartijn642corelib 1.0.19 or above, and below 1.1.0

**Comment by SuperMartijn642** [comment] 2023-03-15 11:17
Duplicate of #3

**Closed as completed by SuperMartijn642** 2023-03-15 11:17 UTC
Labels: bug
